interface State {
  id: number;
  name: string;
}
interface District {
  id: number;
  name: string;
  stateId: number;
}

interface Village {
  id: number;
  name: string;
  districtId: number;
}


interface NepalData {
  states: State[];
  districts: District[];
  villages: Village[];
}


export const nepalData: NepalData = {
  states: [
    { id: 1, name: "Koshi" },
    { id: 2, name: "Madhesh" },
    { id: 3, name: "Bagmati" },
    { id: 4, name: "Gandaki" },
    { id: 5, name: "Lumbini" },
    { id: 6, name: "Karnali" },
    { id: 7, name: "Sudurpashchim" },
  ],
  districts: [
    { "id": 1, "name": "Bhojpur", "stateId": 1 },
    { "id": 2, "name": "Dhankuta", "stateId": 1 },
    { "id": 3, "name": "Ilam", "stateId": 1 },
    { "id": 4, "name": "Jhapa", "stateId": 1 },
    { "id": 5, "name": "Khotang", "stateId": 1 },
    { "id": 6, "name": "Morang", "stateId": 1 },
    { "id": 7, "name": "Okhaldhunga", "stateId": 1 },
    { "id": 8, "name": "Panchthar", "stateId": 1 },
    { "id": 9, "name": "Sankhuwasabha", "stateId": 1 },
    { "id": 10, "name": "Solukhumbu", "stateId": 1 },
    { "id": 11, "name": "Sunsari", "stateId": 1 },
    { "id": 12, "name": "Taplejung", "stateId": 1 },
    { "id": 13, "name": "Tehrathum", "stateId": 1 },
    { "id": 14, "name": "Udayapur", "stateId": 1 },
    { "id": 15, "name": "Bara", "stateId": 2 },
    { "id": 16, "name": "Dhanusha", "stateId": 2 },
    { "id": 17, "name": "Mahottari", "stateId": 2 },
    { "id": 18, "name": "Parsa", "stateId": 2 },
    { "id": 19, "name": "Rautahat", "stateId": 2 },
    { "id": 20, "name": "Saptari", "stateId": 2 },
    { "id": 21, "name": "Sarlahi", "stateId": 2 },
    { "id": 22, "name": "Siraha", "stateId": 2 },
    { "id": 23, "name": "Kathmandu", "stateId": 3 },
    { "id": 24, "name": "Lalitpur", "stateId": 3 },
    { "id": 25, "name": "Bhaktapur", "stateId": 3 },
    { "id": 26, "name": "Chitwan", "stateId": 3 },
    { "id": 27, "name": "Rasuwa", "stateId": 3 },
    { "id": 28, "name": "Ramechhap", "stateId": 3 },
    { "id": 29, "name": "Kavre", "stateId": 3 },
    { "id": 30, "name": "Makhwanpur", "stateId": 3 },
    { "id": 31, "name": "Dhading", "stateId": 3 },
    { "id": 32, "name": "Nuwakot", "stateId": 3 },
    { "id": 33, "name": "Sindhupalchoke", "stateId": 3 },
    { "id": 34, "name": "Dolakha", "stateId": 3 },
    { "id": 35, "name": "Sindhuli", "stateId": 3 },
    { "id": 36, "name": "Baglung", "stateId": 4 },
    { "id": 37, "name": "Gorkha", "stateId": 4 },
    { "id": 38, "name": "Kaski", "stateId": 4 },
    { "id": 39, "name": "Lamjung", "stateId": 4 },
    { "id": 40, "name": "Manang", "stateId": 4 },
    { "id": 41, "name": "Mustang", "stateId": 4 },
    { "id": 42, "name": "Myagdi", "stateId": 4 },
    { "id": 43, "name": "Nawalparasi East ", "stateId": 4 },
    { "id": 44, "name": "Parbat", "stateId": 4 },
    { "id": 45, "name": "Syangja", "stateId": 4 },
    { "id": 46, "name": "Tanahun", "stateId": 4 },
    { "id": 47, "name": "Arghakhanchi", "stateId": 5 },
    { "id": 48, "name": "Banke", "stateId": 5 },
    { "id": 49, "name": "Bardiya", "stateId": 5 },
    { "id": 50, "name": "Dang", "stateId": 5 },
    { "id": 51, "name": "Eastern Rukum", "stateId": 5 },
    { "id": 52, "name": "Gulmi", "stateId": 5 },
    { "id": 53, "name": "Kapilvastu", "stateId": 5 },
    { "id": 54, "name": "Parasi", "stateId": 5 },
    { "id": 55, "name": "Palpa", "stateId": 5 },
    { "id": 56, "name": "Pyuthan", "stateId": 5 },
    { "id": 57, "name": "Rolpa", "stateId": 5 },
    { "id": 58, "name": "Rupandehi", "stateId": 5 },
    { "id": 59, "name": "Western Rukum", "stateId": 6 },
    { "id": 60, "name": "Salyan", "stateId": 6 },
    { "id": 61, "name": "Dolpa", "stateId": 6 },
    { "id": 62, "name": "Humla", "stateId": 6 },
    { "id": 63, "name": "Jumla", "stateId": 6 },
    { "id": 64, "name": "Kalikot", "stateId": 6 },
    { "id": 65, "name": "Mugu", "stateId": 6 },
    { "id": 66, "name": "Surkhet", "stateId": 6 },
    { "id": 67, "name": "Dailekh", "stateId": 6 },
    { "id": 68, "name": "Jajarkot", "stateId": 6 },
    { "id": 69, "name": "Achham", "stateId": 7 },
    { "id": 70, "name": "Baitadi", "stateId": 7 },
    { "id": 71, "name": "Bajhang", "stateId": 7 },
    { "id": 72, "name": "Bajura", "stateId": 7 },
    { "id": 73, "name": "Dadeldhura", "stateId": 7 },
    { "id": 74, "name": "Darchula", "stateId": 7 },
    { "id": 75, "name": "Doti", "stateId": 7 },
    { "id": 76, "name": "Kailali", "stateId": 7 },
    {"id":77, "name":"Kanchanpur District", "stateId":7}
  ],

  villages: [
    { id: 1, name: "Bhojpur", districtId: 1 },
    { id: 2, name: "Shadanand", districtId: 1 },
    { id: 3, name: "Hatuwagadhi", districtId: 1 },
    { id: 4, name: "Ramprasad Rai", districtId: 1 },
    { id: 5, name: "Aamchok", districtId: 1 },
    { id: 6, name: "Tyamke Maiyunm", districtId: 1 },
    { id: 8, name: "Arun Gaunpalika", districtId: 1 },
    { id: 9, name: "Pauwadungma", districtId: 1 },
    { id: 10, name: "Salpasilichho", districtId: 1 },
    { id: 11, name: "Dhankuta", districtId: 2 },
    { id: 12, name: "Pakhribas", districtId: 2 },
    { id: 13, name: "Mahalaxmi", districtId: 2 },
    { id: 14, name: "Sangurigadhi", districtId: 2 },
    { id: 15, name: "Chaubise", districtId: 2 },
    { id: 16, name: "Shahidbhumi", districtId: 2 },
    { id: 17, name: "Chhathar Jorpati", districtId: 2 },
    { id: 18, name: "Ilam", districtId: 3 },
    { id: 19, name: "Deumai", districtId: 3 },
    { id: 20, name: "Mai Municipality", districtId: 3 },
    { id: 21, name: "Suryodaya", districtId: 3 },
    { id: 22, name: "Phakphokthum", districtId: 3 },
    { id: 23, name: "Mai Jogmai", districtId: 3 },
    { id: 24, name: "Chulachuli", districtId: 3 },
    { id: 25, name: "Rong", districtId: 3 },
    { id: 26, name: "Mangsebung", districtId: 3 },
    { id: 27, name: "Sandakpur", districtId: 3 },
     { id: 28, name: "Mechinagar Municipality", districtId: 4 },
    { id: 29, name: "Bhadrapur Municipality", districtId: 4 },
    { id: 30, name: "Birtamod Municipality", districtId: 4 },
    { id: 31, name: "Arjundhara Municipality", districtId: 4 },
    { id: 32, name: "Kankai Municipality", districtId: 4 },
    { id: 33, name: "Shivasatakshi Municipality", districtId: 4 },
    { id: 34, name: "Gauradaha Municipality", districtId: 4 },
    { id: 35, name: "Damak Municipality", districtId: 4 },
    { id: 36, name: "Buddhashanti Rural Municipality", districtId: 4 },
    { id: 37, name: "Haldibari Rural Municipality", districtId: 4 },
    { id: 38, name: "Kachankawal Rural Municipality", districtId: 4 },
    { id: 39, name: "Barhadashi Rural Municipality", districtId: 4 },
    { id: 40, name: "Jhapa Rural Municipality", districtId: 4 },
    { id: 41, name: "Gauriganj Rural Municipality", districtId: 4 },
    { id: 42, name: "Kamal Rural Municipality", districtId: 4 },
    { id: 43, name: "Diktel Rupakot Majhuwagadhi", districtId: 5 },
    { id: 44, name: "Halesi Tuwachung", districtId: 5 },
    { id: 45, name: "Khotehang", districtId: 5 },
    { id: 46, name: "Diprung", districtId: 5 },
    { id: 47, name: "Aiselukharka", districtId: 5 },
    { id: 48, name: "Jantedhunga", districtId: 5 },
    { id: 49, name: "Kepilasgadhi", districtId: 5 },
    { id: 50, name: "Barahpokhari", districtId: 5 },
    { id: 51, name: "Rawabesi", districtId: 5 },
    { id: 52, name: "Sakela", districtId: 5 },
     { id: 53, name: "Biratnagar Metropolitan City", districtId: 6 },
    { id: 54, name: "Sundar Haraicha Municipality", districtId: 6 },
    { id: 55, name: "Belbari Municipality", districtId: 6 },
    { id: 56, name: "Pathari-Sanischare Municipality", districtId: 6 },
    { id: 57, name: "Urlabari Municipality", districtId: 6 },
    { id: 58, name: "Rangeli Municipality", districtId: 6 },
    { id: 59, name: "Letang Bhogateni Municipality", districtId: 6 },
    { id: 60, name: "Ratuwamai Municipality", districtId: 6 },
    { id: 61, name: "Sunawarshi Municipality", districtId: 6 },
    { id: 62, name: "Kerabari Rural Municipality", districtId: 6 },
    { id: 63, name: "Miklajung Rural Municipality", districtId: 6 },
    { id: 64, name: "Kanepokhari Rural Municipality", districtId: 6 },
    { id: 65, name: "Budhiganga Rural Municipality", districtId: 6 },
    { id: 66, name: "Gramthan Rural Municipality", districtId: 6 },
    { id: 67, name: "Katahari Rural Municipality", districtId: 6 },
    { id: 68, name: "Dhanpalthan Rural Municipality", districtId: 6 },
    { id: 69, name: "Jahada Rural Municipality", districtId: 6 },
    { id: 70, name: "Siddhicharan Municipality", districtId: 7 },
    { id: 71, name: "Champadevi Rural Municipality", districtId: 7 },
    { id: 72, name: "Sunkoshi Rural Municipality", districtId: 7 },
    { id: 73, name: "Likhu Rural Municipality", districtId: 7 },
    { id: 74, name: "Chisankhugadhi Rural Municipality", districtId: 7 },
    { id: 75, name: "Molung Rural Municipality", districtId: 7 },
    { id: 76, name: "Khijidemba Rural Municipality", districtId: 7 },
    { id: 77, name: "Manebhanjyang Rural Municipality", districtId: 7 },
    { id: 78, name: "Phidim Municipality", districtId: 8 },
    { id: 79, name: "Hilihang Rural Municipality", districtId: 8 },
    { id: 80, name: "Kummayak Rural Municipality", districtId: 8 },
    { id: 81, name: "Miklajung Rural Municipality", districtId: 8 },
    { id: 82, name: "Phalelung Rural Municipality", districtId: 8 },
    { id: 83, name: "Phalgunanda Rural Municipality", districtId: 8 },
    { id: 84, name: "Tumbewa Rural Municipality", districtId: 8 },
    { id: 85, name: "Yangawarak Rural Municipality", districtId: 8 },
    { id: 86, name: "Bhotkhola", districtId: 9 },
    { id: 87, name: "Chainpur", districtId: 9 },
    { id: 88, name: "Chichila", districtId: 9 },
    { id: 89, name: "Dharmadevi", districtId: 9 },
    { id: 90, name: "Khandbari", districtId: 9 },
    { id: 91, name: "Madi", districtId: 9 },
    { id: 92, name: "Makalu", districtId: 9 },
    { id: 93, name: "Panchkhapan", districtId: 9 },
    { id: 94, name: "Savapokhari", districtId: 9 },
    { id: 95, name: "Silichong", districtId: 9 },
     { id: 96, name: "Solududhkunda", districtId: 10 },
    { id: 97, name: "Dudhakaushika", districtId: 10 },
    { id: 98, name: "Necha Salyan", districtId: 10 },
    { id: 99, name: "Dudhkoshi", districtId: 10 },
    { id: 100, name: "Maha Kulung", districtId: 10 },
    { id: 101, name: "Sotang", districtId: 10 },
    { id: 102, name: "Likhu Pike", districtId: 10 },
    { id: 103, name: "Khumbu Pasanglhamu", districtId: 10 },
     { id: 104, name: "Itahari", districtId: 11 },
    { id: 105, name: "Dharan", districtId: 11 },
    { id: 106, name: "Inaruwa", districtId: 11 },
    { id: 107, name: "Duhabi", districtId: 11 },
    { id: 108, name: "Ramdhuni-Bhasi", districtId: 11 },
    { id: 109, name: "Barahachhetra Municipality", districtId: 11 },
    { id: 110, name: "Koshi", districtId: 11 },
    { id: 111, name: "Gadhi", districtId: 11 },
    { id: 112, name: "Barju", districtId: 11 },
    { id: 113, name: "Bhokraha Narsingh", districtId: 11 },
    { id: 114, name: "Harinagar", districtId: 11 },
    { id: 115, name: "Dewanganj", districtId: 11 },
     { id: 116, name: "Phungling", districtId: 12 },
    { id: 117, name: "Aathrai Tribeni", districtId: 12 },
    { id: 118, name: "Sidingwa", districtId: 12 },
    { id: 119, name: "Phaktanglung", districtId: 12 },
    { id: 120, name: "Mikkwakhola", districtId: 12 },
    { id: 121, name: "Meringden", districtId: 12 },
    { id: 122, name: "Maiwakhola", districtId: 12 },
    { id: 123, name: "Pathibhara Yangwarak", districtId: 12 },
    { id: 124, name: "Sirijangha", districtId: 12 },
    { id: 125, name: "Aathrai", districtId: 13 },
    { id: 126, name: "Chhathar", districtId: 13 },
    { id: 127, name: "Laligurans", districtId: 13 },
    { id: 128, name: "Menchhayayem", districtId: 13 },
    { id: 129, name: "Myanglung", districtId: 13 },
    { id: 130, name: "Phedap", districtId: 13 },
    { id: 131, name: "Triyuga", districtId: 14 },
    { id: 132, name: "Katari", districtId: 14 },
    { id: 133, name: "Chaudandigadhi", districtId: 14 },
    { id: 134, name: "Belaka", districtId: 14 },
    { id: 135, name: "Udayapurgadhi", districtId: 14 },
    { id: 136, name: "Rautamai", districtId: 14 },
    { id: 137, name: "Tapli", districtId: 14 },
    { id: 138, name: "Limchungbung", districtId: 14 },
    { id: 139, name: "Kalaiya Sub Metropolitan City", districtId: 15 },
    { id: 140, name: "Jeetpur Simara Sub Metropolitan City", districtId: 15 },
    { id: 141, name: "Kolhabi Municipality", districtId: 15 },
    { id: 142, name: "Nijgadh Municipality", districtId: 15 },
    { id: 143, name: "Mahagadhimai Municipality", districtId: 15 },
    { id: 144, name: "Simraungadh Municipality", districtId: 15 },
    { id: 145, name: "Pacharauta Municipality", districtId: 15 },
    { id: 146, name: "Pheta Rural Municipality", districtId: 15 },
    { id: 147, name: "Bishrampur Rural Municipality", districtId: 15 },
    { id: 148, name: "Prasauni Rural Municipality", districtId: 15 },
    { id: 149, name: "Adarsh Kotwal Rural Municipality", districtId: 15 },
    { id: 150, name: "Karaiyamai Rural Municipality", districtId: 15 },
    { id: 151, name: "Devtal Rural Municipality", districtId: 15 },
    { id: 152, name: "Parwanipur Rural Municipality", districtId: 15 },
    { id: 153, name: "Baragadhi Rural Municipality", districtId: 15 },
    { id: 154, name: "Suwarna Rural Municipality", districtId: 15 }
    
  ],
};
